import type { CollectionConfig } from 'payload'

export const Bookings: CollectionConfig = {
  slug: 'bookings',
  access: {
    create: () => true,
    read: () => true,
  },
  labels: {
    singular: { cs: 'Rezervace', en: 'Booking', ru: 'Бронирование' },
    plural: { cs: 'Rezervace', en: 'Bookings', ru: 'Бронирования' },
  },
  admin: {
    useAsTitle: 'clientName',
    defaultColumns: ['clientName', 'serviceName', 'date', 'status', 'source', 'altegioVisitStatus'],
    group: { cs: 'Rezervace', en: 'Bookings', ru: 'Бронирования' },
  },
  fields: [
    { name: 'vehicleCategory', type: 'relationship', relationTo: 'vehicle-categories', label: 'Kategorie vozidla' },
    { name: 'service', type: 'relationship', relationTo: 'services', label: 'Služba' },
    { name: 'addons', type: 'relationship', relationTo: 'services', hasMany: true, label: 'Doplňkové služby' },
    { name: 'firstName', type: 'text', label: 'Jméno' },
    { name: 'lastName', type: 'text', label: 'Příjmení' },
    { name: 'email', type: 'email', label: 'Email' },
    { name: 'phone', type: 'text', label: 'Telefon' },
    { name: 'clientName', type: 'text', label: 'Jméno klienta', admin: { description: 'Celé jméno (z Altegio nebo firstName + lastName)' } },
    { name: 'clientPhone', type: 'text', label: 'Telefon klienta' },
    { name: 'serviceName', type: 'text', label: 'Název služby', admin: { description: 'Název služby z Altegio' } },
    { name: 'staffName', type: 'text', label: 'Pracovník' },
    { name: 'date', type: 'date', required: true, label: 'Datum' },
    { name: 'time', type: 'text', label: 'Čas' },
    { name: 'note', type: 'textarea', label: 'Poznámka' },
    { name: 'totalPrice', type: 'number', label: 'Celková cena (Kč)' },
    {
      name: 'status',
      type: 'select',
      options: [
        { label: 'Nová', value: 'new' },
        { label: 'Potvrzená', value: 'confirmed' },
        { label: 'Dokončená', value: 'completed' },
        { label: 'Zrušená', value: 'cancelled' },
      ],
      defaultValue: 'new',
      label: 'Stav',
      admin: { position: 'sidebar' },
    },
    {
      name: 'source',
      type: 'select',
      options: [
        { label: 'Web', value: 'website' },
        { label: 'Altegio', value: 'altegio' },
        { label: 'Telefon', value: 'phone' },
        { label: 'Na místě', value: 'walk-in' },
      ],
      defaultValue: 'website',
      label: 'Zdroj',
      admin: { position: 'sidebar' },
    },
    {
      name: 'altegioVisitStatus',
      type: 'select',
      options: [
        { label: 'Čeká', value: 'waiting' },
        { label: 'Potvrzeno', value: 'confirmed' },
        { label: 'Přišel', value: 'came' },
        { label: 'Nepřišel', value: 'no-show' },
      ],
      label: 'Stav návštěvy (Altegio)',
      admin: { position: 'sidebar' },
    },
    { name: 'altegioRecordId', type: 'number', admin: { position: 'sidebar', description: 'ID záznamu v Altegio' } },
    { name: 'altegioSyncedAt', type: 'date', label: 'Poslední synchronizace', admin: { position: 'sidebar', readOnly: true } },
  ],
}
